SELECT * FROM EMPLOYEE, DEPARTMENT;

-- JOIN 연산(EQUI JOIN)
SELECT * 
FROM EMPLOYEE, DEPARTMENT
WHERE Dnumber = Dno;

-- JOIN 연산(NATURAL JOIN)
SELECT *
FROM EMPLOYEE NATURAL JOIN DEPT_LOCATIONS;

-- JOIN 연산(OUTER JOIN)
SELECT E.Lname 
AS Employee_Name, S.Lname AS Supervisor_Name
FROM Employee
AS E 
LEFT OUTER JOIN EMPLOYEE
AS A ON E.Super_ssn = S.Ssn;